api:
  host: https://otp-mta-prod.camsys-apps.com
  path: /otp/routers/default
  port: 443
  otpApiKey: AGBKDQFGaVjy6gPzQqGdtKNrPBZD0bLi

map:
  initLat: 40.76
  initLon: -73.97
  baseLayers:
    - name: Streets
      url: http://tile.stamen.com/terrain/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
    - name: Stamen Toner Lite
      url: http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'

geocoder:
  boundary:
    rect:
      minLon: -74.62
      maxLon: -73.51
      minLat: 41.11
      maxLat: 40.42
  MAPZEN_KEY: MAPZEN_KEY
  focusPoint:
    lat: 40.76
    lon: -73.97
  # Optional custom Pelias instance (defaults to Mapzen Search)
  # baseUrl: https://geocoder.example.com/pelias/v1

modeGroups:
  - name: Transit
    modes:
      - TRANSIT
      - WALK
  - name: Walk only
    modes:
      - WALK
  - name: Drive only
    modes:
      - CAR
